spring.application.name=mcpclient

# Enable MCP client
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.type=ASYNC
# Streamable HTTP connection to your MCP server
spring.ai.mcp.client.streamable-http.connections.symptomBuddyMCP.url=http://localhost:8081/
spring.ai.mcp.client.streamable-http.connections.symptomBuddyMCP.request-timeout=30s


# Azure OpenAI configuration
spring.ai.azure.openai.api-key=${AZURE_AI_KEY}
spring.ai.azure.openai.endpoint=https://shubhamaiapps.openai.azure.com/
spring.ai.azure.openai.chat.options.deployment-name=gpt-4o
